// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCONYthjdTflpZ8Ky460sunjSMa_wp0-Do',
    appId: '1:998574827952:web:4212e1382a24fb7ded0e75',
    messagingSenderId: '998574827952',
    projectId: 'evently-74b37',
    authDomain: 'evently-74b37.firebaseapp.com',
    storageBucket: 'evently-74b37.firebasestorage.app',
    measurementId: 'G-LPYYH7H9SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmp_5I-PHsZ5rVh9c1PJMw9fQqzyILY7o',
    appId: '1:998574827952:android:40db438de299d301ed0e75',
    messagingSenderId: '998574827952',
    projectId: 'evently-74b37',
    storageBucket: 'evently-74b37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL_oYBSh9wycYIS6qnVQkdMQUpVSd_RnY',
    appId: '1:998574827952:ios:a4527532a4cd68aeed0e75',
    messagingSenderId: '998574827952',
    projectId: 'evently-74b37',
    storageBucket: 'evently-74b37.firebasestorage.app',
    iosBundleId: 'com.example.eventFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL_oYBSh9wycYIS6qnVQkdMQUpVSd_RnY',
    appId: '1:998574827952:ios:a4527532a4cd68aeed0e75',
    messagingSenderId: '998574827952',
    projectId: 'evently-74b37',
    storageBucket: 'evently-74b37.firebasestorage.app',
    iosBundleId: 'com.example.eventFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCONYthjdTflpZ8Ky460sunjSMa_wp0-Do',
    appId: '1:998574827952:web:3c8a635dfddffb68ed0e75',
    messagingSenderId: '998574827952',
    projectId: 'evently-74b37',
    authDomain: 'evently-74b37.firebaseapp.com',
    storageBucket: 'evently-74b37.firebasestorage.app',
    measurementId: 'G-YTTK533DMQ',
  );
}
